### PR TITLE
Update talk.py

### PR DESCRIPTION
**Pull request by Don-Citron**
I mostly added $verify responses, as they were quite outdated, some new filters for the $say, and maybe some stuff here and there? I don't quite remember. I know very little python and mostly just copied existent formatting, so you can double check if you don't trust me. Nobody does. Not even my own mother. But that's irrelevant. 👍

### CODE REVIEW

**Comment by MrSquirrelDeDuck** [comment]
I'm not sure why "holding hands" is added to the $say blacklist, it's probably just something I don't understand.
One thing I did notice, in the $verify command all the pride roles and the "CVC gang" role have capital letters in the role name, and since the role names get converted to lowercase, those ones will never get chosen.

**Comment by Don-Citron** [comment]
"holding hands" is a joke, meant to be hyperbolic.
I fixed the caps. That was a complete brainfart, sorry

**Comment by Don-Citron** [comment]
I also kind of expected somebody to remove "holding hands" from the filter

**Comment by MrSquirrelDeDuck** [comment]
>  I fixed the caps. That was a complete brainfart, sorry

Don't worry, lol. [I've made the exact same mistake before.](https://github.com/Melodie3/Machine-Mind/pull/35)

**Pull request merged**
